# Generated by Django 4.0.6 on 2024-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(max_length=500)),
                ('fileName', models.CharField(max_length=600)),
                ('fileSize', models.BigIntegerField()),
                ('totalChunks', models.IntegerField(default=0)),
                ('chunkIndex', models.IntegerField(default=0)),
                ('path', models.FileField(upload_to='videos')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
